### ISSUE TITLE
`FlashGambleModule`崩溃

### ISSUE THREAD

**Issue by Deleeete** [KLG-Software-Development/klbot#110]
错误信息：

```
异常信息：
JsonDeserializationException：解析的对象数据意外为null

调用栈：
   at klbotlib.MessageServer.Mirai.MiraiMessageServer.GetMessageFromID(Int64 id)
   at klbotlib.Modules.FlashGambleModule.Processor(Message msg, String filterOut)
   at klbotlib.Modules.Module.ProcessMessage(Message msg, String filterOut)
```

**Comment by Deleeete** [comment]
原因：mirai HTTP api更新
以后再也不更mirai服务器了...纯纯自找麻烦
