### ISSUE TITLE
主循环有几率报错：[Error]消息循环线程错误: Error converting value "/{SOME_GUID}" to type 'System.Int64'. Path 'data[0].messageChain[1].id', line 1, position 173.

### ISSUE THREAD

**Issue by Deleeete** [KLG-Software-Development/klbot#14]
从控制台输出上看，发生时无征兆，也没有消息线程重启之外其他的后续效果

**Comment by Deleeete** [comment]
根据时间戳倒查，有可能是其他应用的分享消息触发这类错误。

**Comment by Deleeete** [comment]
> 根据时间戳倒查，有可能是其他应用的分享消息触发这类错误。

经过测试，上述假说被推翻

**Comment by Deleeete** [comment]
发现时间戳是北京时间，所以之前的消息溯源查错了。
重新倒查后的新猜想：上传群文件会触发这个错误。

**Comment by Deleeete** [comment]
> 发现时间戳是北京时间，所以之前的消息溯源查错了。 重新倒查后的新猜想：上传群文件会触发这个错误。

的确如此。调用栈如下：
```
[Error]消息循环线程错误: Error converting value "/822f6862-6d81-11ec-816f-5452007b25f5" to type 'System.Int64'. Path 'data[0].messageChain[1].id', line 1, position 171.
调用栈：
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at klbotlib.MessageServer.Mirai.MiraiMessageServer.FetchMessages()
   at klbotlib.KLBot.MsgLoop(ManualResetEvent waitForPauseMsgLoopSignal)
```
综合异常的具体内容，已经可以得出初步结论，即，现在不能假设消息的`id`字段是整数——当消息本体是群文件时，`id`是一串GUID号。实际获取mirai的上传群文件（部分）消息验证了这一点：
```json
{
    "type":"File",
    "id":"/a530cbc2-6d82-11ec-816f-5452007b25f5",
     "name":"FILE.EXT",
     "size":8077
}
```
而在KLBot框架中其对应的对象为
```CSharp
namespace klbotlib.MessageServer.Mirai.JsonPrototypes
{
    /// <summary>
    /// 直接从JSON解析的消息对象
    /// </summary>
    internal class JMiraiMessage
    {
        public string type;
        public long id;    //<---- 反序列化出错位置
        public long time;
        public long target;
        public string text;
        public string url;
    }
}
```
这主要引出两个本质问题：
1. 框架没有对群文件消息提供支持；
2. 框架没有为JSON反序列化提供**合适的**异常处理，i.e. 虽然提供了但是有较大问题。

将为这两个问题分别开新的issue，然后关掉这一个。

**Comment by Deleeete** [comment]
#17

**Comment by Deleeete** [comment]
已添加对应issue：
对群文件消息提供支持 #17 
为JSON解析提供合适的异常处理 #18
