### ISSUE TITLE
消息循环线程空引用异常

### ISSUE THREAD

**Issue by Deleeete** [KLG-Software-Development/klbot#22]
调试信息
```
[Error]消息循环线程错误: Object reference not set to an instance of an object.
调用栈：
   at klbotlib.MessageServer.Mirai.MiraiMessageFactory.CalcMessageType(JMiraiMessagePackage msg_package, List`1& targets)
   at klbotlib.MessageServer.Mirai.MiraiMessageFactory.BuildMessage(JMiraiMessagePackage msg_package)
   at klbotlib.MessageServer.Mirai.MiraiMessageServer.<>c__DisplayClass5_0.<FetchMessages>b__1(JMiraiMessagePackage jmsg)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at klbotlib.MessageServer.Mirai.MiraiMessageServer.FetchMessages()
   at klbotlib.KLBot.MsgLoop(ManualResetEvent waitForPauseMsgLoopSignal)
```

该错误同样会持续导致消息循环线程自动重启失败。更严重的是这会（以某种方式）绕过启动时“只处理最后一条消息”的机制，导致重启后回复停止期间的所有消息。
因此这个问题引出另外3个issue：
1. `FetchMessages()`需要一个大try-catch块，控制所有已知和未知的异常；
2. 重启只处理最后一条消息机制应转移到消息循环线程层次；
3. 消息循环线程退出时应尝试发送通知到所有监听群。

倒查查不到任何特殊的消息类型，所以无法尝试复现，只能添加额外调试代码并等待问题再次出现。

**Comment by Deleeete** [comment]
已添加新issue：MiraiMessageServer.FetchMessages()中调用BuildMessage()的部分需要更多异常处理 #23

**Comment by Deleeete** [comment]
已添加新issue： 重启只处理最后一条消息机制应转移到消息循环线程层次 #24

**Comment by Deleeete** [comment]
利用issue #23 和相应的PR #25，现在确定空引用异常的触发方法为撤回消息。

**Comment by Deleeete** [comment]
问题出在如下对象：
```CSharp
namespace klbotlib.MessageServer.Mirai.JsonPrototypes
{
    /// <summary>
    /// 直接从JSON解析出的消息包对象
    /// </summary>
    internal class JMiraiMessagePackage
    {
        public string type;
        public JMiraiMessage[] messageChain;    //<=== 在 “撤回消息”的json中，此字段为null
        public JMiraiUser sender;                        //<=== 在 “撤回消息”的json中，此字段为null
    }
}
```
当这两个字段为`null`时，运行到如下代码中就会抛出空引用异常：
```CSharp
private static Type CalcMessageType(JMiraiMessagePackage msg_package, out List<long> targets)
{
//------省略------
        foreach (var sub_msg in msg_package.messageChain)    //MiraiMessageFactory.cs:50
//------省略------
```

这引出的本质问题是，没有对撤回消息提供框架支持。计划添加相应的新issue然后关掉这个。

当然，在对撤回消息的支持完成之前，我们仍然需要绕开这个问题。另一方面，这只能解决撤回消息这一种情况——而还可能有其他消息也会含null字段。因此，除此之外，还需要增加更复杂的逻辑，以应对一切JSON中`messageChain`为null的可能性。

具体来说，应该仅在`type`为已知几种类型时假设`messageChain`不为`null`，并且走原本普通消息的构建流程。

**Comment by Deleeete** [comment]
已添加新issue：对撤回消息提供框架支持 #29
